# Generated by Django 4.1.3 on 2022-11-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('flour_qt', models.IntegerField(null=True)),
                ('eggs', models.IntegerField(null=True)),
                ('sugar', models.IntegerField(null=True)),
                ('cocoa', models.IntegerField(null=True)),
                ('oil', models.IntegerField(null=True)),
                ('butter', models.IntegerField(null=True)),
                ('pumpkin', models.IntegerField(null=True)),
                ('carrot', models.IntegerField(null=True)),
                ('spices', models.IntegerField(null=True)),
                ('honey', models.IntegerField(null=True)),
                ('mapel_sirup', models.IntegerField(null=True)),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
            ],
        ),
        migrations.CreateModel(
            name='Cream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('whipped_cream', models.IntegerField(null=True)),
                ('sour_cream', models.IntegerField(null=True)),
                ('mascarpone', models.IntegerField(null=True)),
                ('milk', models.IntegerField(null=True)),
                ('puding', models.IntegerField(null=True)),
                ('chocolate', models.IntegerField(null=True)),
                ('spices', models.IntegerField(null=True)),
                ('sugar', models.IntegerField(null=True)),
                ('butter', models.IntegerField(null=True)),
                ('colors', models.IntegerField(null=True)),
                ('gelatin', models.IntegerField(null=True)),
                ('honey', models.IntegerField(null=True)),
                ('mapel_sirup', models.IntegerField(null=True)),
                ('fruit', models.ManyToManyField(null=True, to='cake.fruit')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='cream',
            field=models.ManyToManyField(to='cake.cream'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decorations',
            field=models.ManyToManyField(to='cake.decoration'),
        ),
        migrations.AddField(
            model_name='cake',
            name='fruit',
            field=models.ManyToManyField(to='cake.fruit'),
        ),
    ]
