# Generated by Django 4.1.3 on 2022-11-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cream',
            name='fruit',
            field=models.ManyToManyField(to='cake.fruit'),
        ),
    ]
