# Generated by Django 4.1.3 on 2022-11-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_cream_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour', models.IntegerField(null=True)),
                ('egg', models.IntegerField(null=True)),
                ('sugar', models.IntegerField(null=True)),
                ('cocoa', models.IntegerField(null=True)),
                ('oil', models.IntegerField(null=True)),
                ('butter', models.IntegerField(null=True)),
                ('pumpkin', models.IntegerField(null=True)),
                ('carrot', models.IntegerField(null=True)),
                ('spices', models.IntegerField(null=True)),
                ('honey', models.IntegerField(null=True)),
                ('mapel_sirup', models.IntegerField(null=True)),
                ('whipped_cream', models.IntegerField(null=True)),
                ('sour_cream', models.IntegerField(null=True)),
                ('mascarpone', models.IntegerField(null=True)),
                ('milk', models.IntegerField(null=True)),
                ('puding', models.IntegerField(null=True)),
                ('chocolate', models.IntegerField(null=True)),
                ('colors', models.IntegerField(null=True)),
                ('gelatin', models.IntegerField(null=True)),
                ('marzipan', models.IntegerField(null=True)),
                ('fondant', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sponge',
            old_name='flour_qt',
            new_name='flour',
        ),
    ]
