# Generated by Django 4.1.3 on 2022-11-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_remove_cream_fruit_delete_pricelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='eggs_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cake',
            name='milk_free',
            field=models.BooleanField(default=False),
        ),
    ]
