# Generated by Django 4.1.3 on 2022-11-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('cake', '0006_alter_cake_eggs_free_alter_cake_milk_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
