# Generated by Django 4.1.3 on 2022-11-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_cake_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sachr_cake', models.IntegerField(default=0)),
                ('schwarzwald_cake', models.IntegerField(default=0)),
                ('chocolate_cake', models.IntegerField(default=0)),
                ('vanilla_cake', models.IntegerField(default=0)),
                ('fruit_cake', models.IntegerField(default=0)),
                ('cheesecake', models.IntegerField(default=0)),
                ('carrot_cake', models.IntegerField(default=0)),
                ('pumpkin_cake', models.IntegerField(default=0)),
            ],
        ),
    ]
