# Generated by Django 4.1.3 on 2022-11-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='img',
            field=models.CharField(default='../assets/fox.png', max_length=200),
        ),
    ]
