# Generated by Django 4.1.3 on 2022-11-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0011_alter_cake_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
