# Generated by Django 4.1.3 on 2022-11-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0012_delete_pricelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='order',
        ),
    ]
