# Generated by Django 4.1.3 on 2022-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0013_remove_cake_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='img',
            field=models.CharField(default='IMG_2933.2f5e737a.jpg', max_length=200),
        ),
    ]
