# Generated by Django 4.1.3 on 2022-11-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0013_remove_cake_order'),
        ('order', '0002_order_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cakes',
            field=models.ManyToManyField(to='cake.cake'),
        ),
    ]
